# Generated by Django 3.1.4 on 2020-12-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('project', models.CharField(blank=True, max_length=120)),
                ('outstanding', models.BooleanField(default=True)),
                ('short_description', models.CharField(blank=True, max_length=120)),
                ('long_description', models.TextField(blank=True)),
                ('code_block', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('ref_link', models.TextField(blank=True)),
                ('technology', models.CharField(choices=[(None, '---Select One---'), ('C', 'C'), ('C#', 'C#'), ('C++', 'C++'), ('CSS', 'CSS'), ('Dart', 'Dart'), ('Go', 'Go'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Kotlin', 'Kotlin'), ('HTML', 'HTML'), ('Perl', 'Perl'), ('PHP', 'PHP'), ('Python', 'Python'), ('R', 'R'), ('Ruby', 'Ruby'), ('Rust', 'Rust'), ('Scala', 'Scala'), ('Swift', 'Swift')], default=1, max_length=15)),
            ],
        ),
    ]
